name: Build DOCs
on:
  workflow_dispatch: {}
jobs:
  build:
    name: build-doc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install template
      run: |
        python -m pip install --upgrade pip
        pip install furo

    - name: Install dependencies
      run: |
          pip install selenium phonenumbers asyncio
          cd docs
          make clean html
          make html
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name github-actions[bot]
          git add .
          git commit -m "Update docs"
          git push -u origin main
          cd ..
          mv docs/_build/html/* .
          rm -rf docs venv __pycache__ crazyshit .gitignore LICENSE .github README.md pyproject.toml
          touch .nojekyll
          git checkout --orphan gh-pages
          git add . -A
          git commit -m "Update documentation"
          git push origin gh-pages --force